global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.3
  publish_frequency: 0.3
  transform_tolerance: 0.5
  track_unknown_space: true

  plugins:
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}

  # STATIC MAP
  static_layer:
    map_topic: /map
    subscribe_to_updates: true

  # OBSTACLES (Laser)
  obstacle_layer:
    observation_sources: scan depth_cloud

    scan:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      inf_is_valid: true

    depth_cloud:
      data_type: PointCloud2
      topic: /obstacles/depth_points_filtered
      marking: true
      clearing: false                 # WICHTIG: Depth nur markieren
      min_obstacle_height: 0.01
      max_obstacle_height: 0.30
      observation_persistence: 1.0

  # INFLATION
  inflation:
    inflation_radius: 0.18
    cost_scaling_factor: 5.0