local_costmap:
  global_frame: odom           # map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5

  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: scan depth_cloud

    scan:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      inf_is_valid: true
      obstacle_range: 3.0
      raytrace_range: 3.5

    depth_cloud:
      data_type: PointCloud2
      topic: /obstacles/depth_points_filtered
      marking: true
      clearing: false
      min_obstacle_height: 0.01
      max_obstacle_height: 0.30
      observation_persistence: 1.0

  inflation:
    inflation_radius: 0.15
    cost_scaling_factor: 2.5